<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = ['Harare', 'Chitungwiza', 'Epworth','Bulawayo',
        'Birchenough Bridge',
        'Buhera',
        'Cashel',
        'Chimanimani',
        'Chipinge',
        'Chisumbanje',
        'Craigmore',
        'Dorowa',
        'Gumira',
        'Hauna',
        'Headlands',
        'Juliasdale',
        'Junction Gate',
        'Massi Kessi',
        'Mount Selinda',
        'Murambinda',
        'Mutambara',
        'Mutare',
        'Nyanga',
        'Nyanyadzi',
        'Nyazura',
        'Odzi',
        'Penhalonga',
        'Rusape',
        'Sakubva',
        'Sanyatwe',
        'Stapleford',
        'Tandaai',
        'Tizvione',
        'Troutbeck',
        'Tsanzaguru',
        'Tsunga',
        'Watsomba',
        'Zimunya','Bindura',
        'Centenary',
        'Concession',
        'Domboshava',
        'Guruve',
        'Jumbo',
        'Kanyemba',
        'Madziwa Mine',
        'Manhenga',
        'Mazowe',
        'Melfort',
        'Mount Darwin',
        'Mukumbura',
        'Mushumbi Pools',
        'Musweswenedi',
        'Muzarabani District',
        'Mvurwi',
        'Shamva',
        'Tengenenge','Arcturus',
        'Beatrice',
        'Bromley',
        'Chivhu',
        'Goromonzi',
        'Kotwa',
        'Macheke',
        'Marondera',
        'Mount Hampden',
        'Murewa',
        'Mutoko',
        'Nyabira',
        'Nyamapanda',
        'Rocky Spruit',
        'Ruwa','Alaska',
        'Banket',
        'Battlefields',
        'Caesar',
        'Chakari',
        'Charara',
        'Chegutu',
        'Chirundu',
        'Chinhoyi',
        'Darwendale',
        'Eiffel Flats',
        'Eldorado',
        'Feock',
        'Gadzema',
        'Golden Valley',
        'Kadoma',
        'Kariba',
        'Karoi',
        'Kildonan',
        'Kutama',
        'Lion\'s Den',
        'Madadzi',
        'Magunje',
        'Makuti',
        'Makwiro',
        'Mhangura',
        'Mubayira',
        'Muriel',
        'Murombedzi',
        'Mutorashanga',
        'Muzvezve',
        'Mwami',
        'Norton',
        'Raffingora',
        'Sanyati',
        'Selous',
        'Shackleton',
        'Tashinga',
        'Tengwe',
        'Trelawney',
        'Umsweswe',
        'Vanad',
        'Venice',
        'Vuti',
        'Zave','Baradzanwa',
        'Boora',
        'Chatsworth',
        'Chibwedziva',
        'Chigumisirwa',
        'Chikuku',
        'Chikukutu',
        'Chiredzi',
        'Chiremwaremwa',
        'Chirorwe',
        'Devure',
        'Devure Ranch',
        'Felixburg',
        'Gurajena',
        'Gwengwerere',
        'Magocha',
        'Magomana',
        'Maranda',
        'Marozva (a)',
        'Marozva (b)',
        'Mashava',
        'Mashoko',
        'Masvingo',
        'Matibi',
        'Matsvange',
        'Mazungunye',
        'Mbizi',
        'Mukore',
        'Mungezi',
        'Mupamande',
        'Mupandawana',
        'Murwira',
        'Museti',
        'Mutikizizi',
        'Ndanga',
        'Negovano',
        'Neshuro',
        'Ngundu',
        'Nyahunda',
        'Nyarushiri',
        'Renco',
        'Rutenga',
        'Sango',
        'Shenjere Village',
        'Triangle',
        'Tswiza','Bembezi',
        'Binga village',
        'Bradfield',
        'Dagamela',
        'Dete',
        'Eastnor',
        'Inyati',
        'Jotsholo',
        'Kamativi',
        'Kariyangwe',
        'Kazungula',
        'Lonely Mine',
        'Lower Gwelo',
        'Matetsi',
        'Mbuma',
        'Mlibizi',
        'Mpandamatenga',
        'Nkayi',
        'Nyamandhlovu',
        'Queens Mine',
        'Shangani',
        'Turk Mine',
        'Victoria Falls','Alisupi',
        'Antelope Mine',
        'Bezu',
        'Blanket Mine',
        'Brunapeg',
        'Colleen Bawn',
        'Esigodini',
        'Esimbomvu',
        'Figtree',
        'Filabusi',
        'Fumukwe',
        'Gwai',
        'Gwanda',
        'Hwali',
        'Kezi',
        'Lutumba',
        'Manama',
        'Marinoha',
        'Marula',
        'Mazunga',
        'Plumtree',
        'Towla',
        'Tuli',
        'Vubachikwe',
        'West Nicholson','Cha Cha Cha Township',
        'Columbina Rural Service Center',
        'Commoner',
        'Empress Mine Township',
        'Gokwe centre',
        'Gweru',
        'Gweru District',
        'Kwekwe',
        'Lalapanzi',
        'Marira',
        'Munyati',
        'Mvuma',
        'Redcliff',
        'Shurugwi',
        'Shurugwi Rural Areas',
        'Silobela',
        'Somabhula',
        'Vungu Rural District Council',
        'Zhombe',
        'Zvishavane'];



        foreach($cities as $city){
            City::create([
                'name'=>$city,
            ]);
        }
    }
    
}
